require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - example.rb
    - dev/**/*
    - debug.rb

# Allow `$stderr.puts`, we don't want `warn`
Style/StderrPuts:
  Exclude:
    - 'lib/colsole.rb'

# Allow optional boolean parameter as a non-keyword argument.
# Changing this breaks the interface
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/colsole.rb'

# TODO: Remove when compatibility layer is removed
RSpec/FilePath:
  Exclude:
    - spec/colsole/compat_spec.rb

# TODO: Remove when compatibility layer is removed
Metrics/ModuleLength:
  Exclude:
    - lib/colsole.rb
