require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - example.rb
    - dev/**/*
    - debug.rb

# Allow `$stderr.puts`, we don't want `warn`
Style/StderrPuts:
  Exclude:
    - 'lib/colsole.rb'

# Allow optional boolean parameter as a non-keyword argument.
# Changing this breaks the interface
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/colsole.rb'

# Allow a longer module
Metrics/ModuleLength:
  Exclude:
    - lib/colsole.rb
